name: tittam_rev1
description: this tittam app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #firebase_database: ^3.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: ^0.2.2
  flutter_screenutil: ^0.5.3
  connectivity: 0.4.6+2
  flutter_offline: ^0.3.0
  flutter_line_sdk:
  http: ^0.12.0+4
  jaguar_jwt: ^2.1.6
  sqflite: any
  path_provider: any
  intl: ^0.16.1 
  firebase_database: ^3.1.1
  firebase_core: any
  #firebase_auth: ^0.15.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/logo.png
    - images/btn_login_press.png
    - images/btn_line_thai.png
    - images/kusrc_logo.png
    - images/pty7_logo.png
    - images/camera_logo.png
    - images/tittam_logo.png
    - images/partner_logo.png
    - images/icon_manu.png
    - images/icon_share.png
    - images/user_pic.png
    - images/line_logo.png
    - images/body_healthy.png
    - images/body_obese.png
    - images/body_over.png
    - images/body_under.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Kanit
       fonts:
         - asset: fonts/Kanit-Regular.ttf
         - asset: fonts/Kanit-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
